// Metodos depreciados que interferem diretamente no DOM
String.prototype.anchor()
String.prototype.big()
String.prototype.blink()
String.prototype.bold()
String.prototype.fixed()
String.prototype.fontcolor()
String.prototype.fontsize()
String.prototype.italics()
String.prototype.link()
String.prototype.small()
String.prototype.sub()
String.prototype.sup()

// Metodos menos utilizados
String.prototype.codePointAt()
String.fromCodePoint()
String.prototype.normalize()
String.prototype.localeCompare()
String.prototype.toLocaleLowerCase()
String.prototype.toLocaleUpperCase()